### PR TITLE
Upgrade pip to "latest" version

### PR DESCRIPTION
**Pull request by jschaul**
Hi,
thanks for your pip role. We had the problem that, if pip is already installed, it would not upgrade unless a specific version number is specified. This pull request should address that and makes the following changes:

- Make version checks idempotent
- Make sure to upgrade to latest version if `pip_version : "LATEST"` or if variable is `None`

### CODE REVIEW

**Comment by bobbyrenwick** [comment]
Oh, I just merged #3 that also had fixes for making the role idempotent too and now it won't let me merge this. I don't understand why - there won't be conflicts.

Would you be able to add something to the docs about having `pip_version: "LATEST"` and `pip_version: NONE` please?

**Comment by jschaul** [comment]
Hi, 
I just resolved the merge conflicts through a rebase and added details about the upgrade behaviour when version is set to None or LATEST to readme as you requested.

**Comment by luzfcb** [comment]
@bobbyrenwick what is missing to merge this?

**Comment by bobbyrenwick** [comment]
@luzfcb nothing, I've just been on holiday!

@jschaul thanks for this!

**Comment by luzfcb** [comment]
@bobbyrenwick thanks.

**Pull request merged**
