### PR TITLE
Replace deprecated "sudo" with "become"

### PR DESCRIPTION
**Pull request by binary-data**
When running this role on ansible 2.0.0.2 it shows deprecation warning "[DEPRECATION WARNING]: instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default). This feature will be removed in a future release."

This PR replaces "sudo" with "become"

### CODE REVIEW

**Comment by bobbyrenwick** [comment]
@binary-data this is great thanks, would you be able to merge the latest master into your fork to resolve the conflict and then update `meta/main.yml` to contain `min_ansible_version: 1.9` please?

**Comment by binary-data** [comment]
@bobbyrenwick sure, will do that

**Comment by binary-data** [comment]
Done, you are able to merge

**Comment by bobbyrenwick** [comment]
Thanks @binary-data I will merge and release v2.0.0 tomorrow

**Pull request merged**
